### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by sverx** [kusfo/sms-fxsample#1]
In this:
```
const unsigned char psgInit[] =
{
	0x9F, 0xBF, 0xDF, 0xFF, 0x81, 0x00, 0xA1, 0x00, 0x00, 0xC1, 0x00
};
```
you have two values inverted.
It actually doesn't cause any problem because you've got a zero anyway at the end after 0xC1, but you probably wanted
`0x9F, 0xBF, 0xDF, 0xFF, 0x81, 0x00, 0xA1, 0x00, 0xC1, 0x00, 0xE0`

**Comment by kusfo** [comment]
Thanks for spotting it! I don't remember where I got these values, but I'm fixing it right now.
